### ISSUE TITLE
[PR ADD]  ayushrana83

### ISSUE THREAD

**Issue by ayushrana83** [iamAyushChamoli/hacktoberfest-24#104]
## PR Details
Please provide the following details about your external contribution:

1.  name - Ayush Rana
2.  github username - ayushrana83
3.  external PR number - 63 , 71
4.  link to external PR -  https://github.com/AkshitLakhera/PenCraft-Full-Stack-Blogging-Application/pull/63 , https://github.com/AkshitLakhera/PenCraft-Full-Stack-Blogging-Application/pull/71
6.  external repository -  https://github.com/AkshitLakhera/PenCraft-Full-Stack-Blogging-Application

> Updated UI of sign n and signup page

> added changes for different themes

**Comment by iamAyushChamoli** [comment]
@ayushrana83 you can create a PR to update your details in src/participants. Please make sure that you read the updated README.md to see the updated method of updating your details.
