### ISSUE TITLE
[ISSUE] Update content of CONTRIBUTING.md 

### ISSUE THREAD

**Issue by RishaubKumar** [iamAyushChamoli/hacktoberfest-24#106]
## Description
As new method of adding details for participants is introduced , but the CONTRIBUTING.md still have the old way to do same so it need to be updated for the convenience of contributors.

## Additional Information
update the existing CONTRIBUTING.md so that user could easily update its details. Present a step by step proccess and all the changes which are introduced in the new system.

**Comment by iamAyushChamoli** [comment]
Thank you but Our maintainers are working on this Issue for now.
