### ISSUE TITLE
[ISSUE] Fix inconsistent border of Hacktoberfest image

### ISSUE THREAD

**Issue by shubhanshu-02** [iamAyushChamoli/hacktoberfest-24#108]
Feature

- **What is the current behavior?**: 
The current Hacktoberfest image has rounded corners only on the bottom. However, the top corners are not rounded, creating an inconsistency in the design.

the top part of the 
- **What is the expected behavior?**: 
The top corners of the Hacktoberfest image should also be rounded to maintain uniformity with the bottom corners, providing a cohesive visual appearance.

## Screenshots (if applicable)
![WhatsApp Image 2024-10-06 at 22 40 40_817c0f0c](https://github.com/user-attachments/assets/4bd81b4d-c22c-4be2-af3b-6012bb9a209f)

I’d like to fix this issue. Please assign it to me.

**Comment by iamAyushChamoli** [comment]
@shubhanshu-02 you can start working on this issue
