### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Shrutibansal22** [iamAyushChamoli/hacktoberfest-24#124]
I want to add stylish and responsive footer for the website.
Kindly assign me this issue under Hacktober fest.

**Comment by iamAyushChamoli** [comment]
@Shrutibansal22 you can start working on this issue and submit a PR

**Comment by Ayaanpathan99** [comment]
hey, @iamAyushChamoli i am interested in this issue,
can you assign this issue to me.

**Comment by iamAyushChamoli** [comment]
@Ayaanpathan99 since @Shrutibansal22 is currently assigned to this issue, this won't be possible. However, if @Shrutibansal22 fails to provide an update within the next 24 hours, I'll have to unassign her on account of unavailability and open this issue up for other ideas from other contributors.
