### ISSUE TITLE
[PR EXTERNAL] Nishant Rana

### ISSUE THREAD

**Issue by NishantRana07** [iamAyushChamoli/hacktoberfest-24#133]
## PR Details

- **Name**: Nishant Rana
- **GitHub Username**: NishantRana07
- **External PR Number**: #168
- **Link to External PR**: https://github.com/tushargupta1504/Medical-Website/pull/168#event-14526018493
- **External Repository**: https://github.com/tushargupta1504/Medical-Website
- **Brief Description of Your Contribution**: Added Logo and responsive Navbar to the project

**Comment by iamAyushChamoli** [comment]
@NishantRana07 you can create a PR to update your participation details to be featured on the leaderboard
