### ISSUE TITLE
[PR ADD] Mohit Rana

### ISSUE THREAD

**Issue by Mohitranag18** [iamAyushChamoli/hacktoberfest-24#135]
## PR Details
Please provide the following details about your external contribution:

- **Name**: Mohit Rana
- **GitHub Username**: mohitranag18
- **External PR Number**: 691
- **Link to External PR**: https://github.com/aditya-bhaumik/Pathsphere/pull/691
- **External Repository**: https://github.com/aditya-bhaumik/Pathsphere
- **Brief Description of Your Contribution**:  

**Details**

- Converted forum-section elements into card format.
- Applied a yellow, white, and grey color theme for consistency with the overall design.
- Implemented a responsive layout using flexbox, where forum-section cards are displayed horizontally and forum-posts are vertically aligned inside each section.
- Added a hover effect to the cards for better interactivity.
- Incorporated media queries to ensure mobile responsiveness, with sections stacking vertically on smaller screens.

**Comment by iamAyushChamoli** [comment]
@Mohitranag18 please create a PR to update your participation details
