### ISSUE TITLE
[ISSUE] Mis-aligned badge section 

### ISSUE THREAD

**Issue by AkshitSalwan** [iamAyushChamoli/hacktoberfest-24#138]
## Description
The section which contains badges based on the contribution to this repo have mis-aligned height for the "Active Contributor"
badge.
- **Is this a bug or a feature request?**: (Bug / Feature)
- **Wha
<img width="1440" alt="Screenshot 2024-10-20 at 12 00 29 PM" src="https://github.com/user-attachments/assets/dd42d1c8-340a-4bd4-b1b5-2492d3faf6ea">
t is the current behavior?**: Longer height than other badges
- **What is the expected behaviour ?**: same height as other two badges

**Comment by AkshitSalwan** [comment]
kindly assign me this issue and add hacktoberfest labels

**Comment by iamAyushChamoli** [comment]
@AkshitSalwan This is not a bug, this was supposed to look that way. Thank you for your time, you can checkout other open issues
