### ISSUE TITLE
[ISSUE] Home Image Not Properly Responsive

### ISSUE THREAD

**Issue by AnasAli30** [iamAyushChamoli/hacktoberfest-24#139]
## Description
 home image does not scale properly on smaller screens, resulting in part of the image being cut off.

- **Is this a bug or a feature request?**: Bug
- **What is the current behavior?**: 
 - On responsive layouts, the home image enlarges beyond its container, causing part of it to be cut off, which looks unattractive.
- **What is the expected behavior?**: 
- The home image should scale appropriately across all screen sizes without cutting off any part of it, ensuring a more responsive and clean look.

![image](https://github.com/user-attachments/assets/c22d4576-147e-413c-89a4-6f59dbeae6b0)

**Comment by AnasAli30** [comment]
@iamAyushChamoli   Please assign me.

**Comment by iamAyushChamoli** [comment]
@AnasAli30 you can start working on this issue

**Comment by AnasAli30** [comment]
@iamAyushChamoli #141
