### ISSUE TITLE
[ISSUE] Badges Tiles Not Centered Properly on Small Screens

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#142]
## Description
On small screens, the Vaunt badges displayed are aligned towards the left side of the screen. It'd be better to center them specifically for smaller screens to ensure consistent design.

- **Is this a bug or a feature request?**: (Bug )
- **What is the current behavior?**:  Badges tiles aligned to the left of the screen
- **What is the expected behavior?**:  Badges tiles should be aligned to the center

## Screenshots (if applicable)
<img width="756" alt="image" src="https://github.com/user-attachments/assets/33c36207-39fd-4864-bf07-89cb4b5aa8eb">

**Comment by AnasAli30** [comment]
@iamAyushChamoli assign me pls

**Comment by AnasAli30** [comment]
@iamAyushChamoli check #143
