### ISSUE TITLE
[ISSUE] Learn more buttons are not working as links

### ISSUE THREAD

**Issue by vineet-53** [iamAyushChamoli/hacktoberfest-24#15]
## Description
Please provide a clear and concise description of the issue or feature you are working on.
Integrating the links listed below on benefits sections so that to redirect the user to the article or blog page where they get to know more about the listed benefits.

- explore open source:
  https://testsigma.medium.com/an-ultimate-guide-to-open-source-contribution-for-beginners-7278952b0b9f

- learn git and github:
  https://www.freecodecamp.org/news/introduction-to-git-and-github/

- compete with your peers:
  https://github.com/explore

- build your github portfolio:
  https://medium.com/@kapil0123/building-your-stunning-github-portfolio-a-step-by-step-guide-a5e8650c5009

- limited edition bages:
https://github.com/drknzz/GitHub-Achievements

- network and create memories:
  https://resources.github.com/events/

- **Is this a bug or a feature request?**: (Feature)
- **What is the current behavior?**:  (learn more button not working as link)
- **What is the expected behavior?**:(Redirect to an article or a blog page to explain more about the benefits)

**Comment by iamAyushChamoli** [comment]
Hi @vineet-53 , For these sections, I would rather prefer dedicated markdown (.md) files that talk about these issues rather than external links. I'll be updating these issues in the ISSUES tab soon.
