### ISSUE TITLE
[ISSUE] Create a markdown file for "Learn More" Button in "Explore Open Source Section"

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#18]
## Description
In the "Explore Open Source" segment of the "ABOUT" section, pressing the "Learn More" button currently does nothing. It'll be helpful to create a markdown file named "Explore.md" in a separate folder titled "abt" that talks about this section more.

- **Is this a bug or a feature request?**: (Feature)
- **What is the current behavior?**: Nothing happens when we click on "Learn More" in Explore Open Source segment
- **What is the expected behavior?**: Users get redirected to a markdown file stored in hacktoberfest-24/abt/Explore.md

## Screenshots (if applicable)
<img width="420" alt="image" src="https://github.com/user-attachments/assets/d9ed2a38-e1c1-4374-b81f-bc752c1e9cb1">

## Additional Information
To learn how to create a Markdown file, either study the format "README.md" is written or check out this video: https://youtu.be/_PPWWRV6gbA?si=qPjeA8te4DkfBo5p

**Comment by uday1508** [comment]
I would like to contribute to this Feature. Could you please assign it to me?

**Comment by iamAyushChamoli** [comment]
Hi @uday1508  I believe you already have a PR assigned to you that is under development? If that's not the case, have you updated the participants log where you can be featured on the Leaderboard? Please revert once you've completed all the steps before being assigned the next Issue.

**Comment by uday1508** [comment]
> Hi @uday1508 I believe you already have a PR assigned to you that is under development? If that's not the case, have you updated the participants log where you can be featured on the Leaderboard? Please revert once you've completed all the steps before being assigned the next Issue.

Sure , I will update it

**Comment by iamAyushChamoli** [comment]
@uday1508 you can start working on this issue now

**Comment by iamAyushChamoli** [comment]
@uday1508 are you working on this issue? If you fail to submit an update within 24 hours, you will be unassigned and another contributor may be asked to fix this issue.

**Comment by iamAyushChamoli** [comment]
Since @uday1508 failed to submit an update within the given time frame, I will open this issue for other contributors

**Comment by shash369** [comment]
Hi,
I hope this message finds you well. If this issue is still available, I would like to work on it.
Could you please assign me this issue under Hacktoberfest 2024? Thank you!
Best regards,

**Comment by RishaubKumar** [comment]
assign it to me with hacktoberfest label!
