### ISSUE TITLE
[ISSUE] ScrollBar Styles

### ISSUE THREAD

**Issue by MishraTanishq619** [iamAyushChamoli/hacktoberfest-24#19]
## Description
Our Scrollbar is not styled. We can add styles to it syncing with the theme.

- **Is this a bug or a feature request?**:  Feature
- **What is the current behavior?**:  We have "No" styles on Scrollbar.
- **What is the expected behavior?**:  Styles of Scrollbar should be aligned with App Theme.

## Assign Me
I want to work on this myself. Please assign it to me for hacktoberfest.

**Comment by MishraTanishq619** [comment]
@iamAyushChamoli can you also add Hactoberfest and Hacktobrfest-Accepted tags Please.

**Comment by iamAyushChamoli** [comment]
@MishraTanishq619 added the hacktoberfest label, hacktoberfest-accepted label will be awarded upon successfully completing a meaningful contribution. Thanks!
