### ISSUE TITLE
[ISSUE] Create a markdown file for "Learn More" Button in "Learn Git & Github" Section

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#20]
## Description
In the "Learn Git & GitHub" segment of the "ABOUT" section, pressing the "Learn More" button currently does nothing. It'll be helpful to create a markdown file named "GitHub_Git.md" in a separate folder titled "abt" that talks about this section more.

- **Is this a bug or a feature request?**: (Feature)
- **What is the current behavior?**: Nothing happens when we click on "Learn More" in Learn Git & GitHub
- **What is the expected behavior?**: Users get redirected to a markdown file stored in hacktoberfest-24/abt/GithHub_Git.md

## Screenshots (if applicable)
<img width="410" alt="image" src="https://github.com/user-attachments/assets/f3b25373-aa4d-4f07-8a4e-3a144e5cc1e9">

## Additional Information
To learn how to create a Markdown file, either study the format "README.md" is written or check out this video: https://youtu.be/_PPWWRV6gbA?si=qPjeA8te4DkfBo5p

**Comment by ManishG04** [comment]
I would like to contribute to this, I just have a doubt about the content so I have to mention why learn Git & Github? or do I have to add references for learning git and github? I can do both of it if you want. This will create a file which will open when the user clicks learn more and then he can read how hacktoberfest and participating in it will help the user learn about Git and Github and hence helping them know the importance of git and github.

**Comment by iamAyushChamoli** [comment]
@ManishG04 Yes, you can start

**Comment by ManishG04** [comment]
okay!! So I will work on how is this a perfect opportunity to learn Git and Github.

**Comment by ManishG04** [comment]
I have completed the task of this issue and created a pull request #46
