### ISSUE TITLE
[ISSUE] Create a Markdown File for "Learn More" Button in Compete With Your Peers Section

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#21]
## Description
In the "Compete With Your Peers" segment of the "ABOUT" section, pressing the "Learn More" button currently does nothing. It'll be helpful to create a markdown file named "Compete.md" in a separate folder titled "abt" that talks about this section more.

- **Is this a bug or a feature request?**: (Feature)
- **What is the current behavior?**: Nothing happens when we click on "Learn More" in Compete with Your Peers segment
- **What is the expected behavior?**: Users get redirected to a markdown file stored in hacktoberfest-24/abt/Compete.md

## Screenshots (if applicable)
<img width="400" alt="image" src="https://github.com/user-attachments/assets/437731e5-a11f-42f4-a1c1-4d162d24c744">

## Additional Information
To learn how to create a Markdown file, either study the format "README.md" is written or check out this video: https://youtu.be/_PPWWRV6gbA?si=qPjeA8te4DkfBo5p

**Comment by imtanujbranch** [comment]
@iamAyushChamoli can you assign this to me ?

**Comment by iamAyushChamoli** [comment]
@imtanujbranch yes you can start

**Comment by imtanujbranch** [comment]
@iamAyushChamoli Should I create a new branch for my changes, or is it okay to work directly on the main branch?

**Comment by iamAyushChamoli** [comment]
@imtanujbranch please refer to the CONTRIBUTING.md for these queries

**Comment by iamAyushChamoli** [comment]
@imtanujbranch are you working on this issue? Please submit an update before 5 October 00:00 AM or this issue will be opened to other contributors.
