### ISSUE TITLE
[ISSUE] Create Markdown File For "Learn More" button in Build Your Github Portfolio Section

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#22]
## Description
In the "Build Your Github Portfolio" segment of the "ABOUT" section, pressing the "Learn More" button currently does nothing. It'll be helpful to create a markdown file named "Portfolio.md" in a separate folder titled "abt" that talks about this section more.

- **Is this a bug or a feature request?**: (Feature)
- **What is the current behavior?**: Nothing happens when we click on "Learn More" in Build Your Github Portfolio segment
- **What is the expected behavior?**: Users get redirected to a markdown file stored in hacktoberfest-24/abt/Portfolio.md

## Screenshots (if applicable)
<img width="418" alt="image" src="https://github.com/user-attachments/assets/82b57ac9-c1c2-4d85-b1e4-dd702743345a">

## Additional Information
To learn how to create a Markdown file, either study the format "README.md" is written or check out this video: https://youtu.be/_PPWWRV6gbA?si=qPjeA8te4DkfBo5p

**Comment by Jayesh-Waghmare** [comment]
Hi @iamAyushChamoli I would like to do this work. Could you please assign it to me? ... Thank you

**Comment by iamAyushChamoli** [comment]
@Jayesh-Waghmare You can start

**Comment by iamAyushChamoli** [comment]
@Jayesh-Waghmare are you working on this issue? If you fail to submit an update within 24 hours, you will be unassigned and another contributor may be asked to fix this issue.

**Comment by SaumyaSubham** [comment]
Hii @iamAyushChamoli 
I want to work on this issue. Kindly assign me this under Hacktoberfest 2024

**Comment by iamAyushChamoli** [comment]
@SaumyaSubham  please avoid spamming the ISSUES and tagging the maintainers for the ISSUES that have already been assigned to other contributors. If the current assignee fails to provide an update in the given time frame, I'll mention it in the comments and open the issue up for other contributors. Until then, please maintain community decorum and avoid spammy comments. Repeated violation might lead to a ban. Thanks!

**Comment by iamAyushChamoli** [comment]
@Jayesh-Waghmare Yes, the link should connect to abt/Portfolio.md

**Comment by iamAyushChamoli** [comment]
Unassigning @Jayesh-Waghmare due to inactivity. This issue is open to other contributors now.

**Comment by Jayesh-Waghmare** [comment]
Sorry but I am currently facing an issue with the authentication of the organization

**Comment by Jayesh-Waghmare** [comment]
@iamAyushChamoli I am already done with the project. Due to that I am being stuck. I am resolving the issue in just a few hours

**Comment by iamAyushChamoli** [comment]
@Jayesh-Waghmare it's been 4 days since you were assigned the issue and you were warned once before about your inactivity. Sorry but we cannot keep the issue on hold for other contributors.

**Comment by SaumyaSubham** [comment]
Hello @iamAyushChamoli 
Can I help out with this?

**Comment by kmahesh18** [comment]
hii @Jayesh-Waghmare  , i would like to work on this...can u assign me?

**Comment by abhayjoshi201** [comment]
I would like to work on this can you assign me!

**Comment by iamAyushChamoli** [comment]
@abhayjoshi201 please start working on the issue
