### ISSUE TITLE
[ISSUE] Create a Markdown File for "Learn More" button for Limited Edition Badge Section

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#23]
## Description
In the "Limited Edition Badge" segment of the "ABOUT" section, pressing the "Learn More" button currently does nothing. It'll be helpful to create a markdown file named "Badge.md" in a separate folder titled "abt" that talks about this section more.

- **Is this a bug or a feature request?**: (Feature)
- **What is the current behavior?**: Nothing happens when we click on "Learn More" in Limited Edition Badge segment
- **What is the expected behavior?**: Users get redirected to a markdown file stored in hacktoberfest-24/abt/Badge.md

## Screenshots (if applicable)
<img width="409" alt="image" src="https://github.com/user-attachments/assets/934dadba-e680-422f-857e-6d7a1ed1bec3">

## Additional Information
To learn how to create a Markdown file, either study the format "README.md" is written or check out this video: https://youtu.be/_PPWWRV6gbA?si=qPjeA8te4DkfBo5p

**Comment by jfmartinz** [comment]
What would be the content of the markdown?

**Comment by jfmartinz** [comment]
can you assign the issue to me?

**Comment by iamAyushChamoli** [comment]
@jfmartinz You can start working on this issue. The content should be a basic explanation of the introduction to our limited time badges (You can check them out on the website) and how these help in incentivizing more participation from contributors

**Comment by iamAyushChamoli** [comment]
@jfmartinz are you working on this issue? If you fail to submit an update within 24 hours, you will be unassigned and another contributor may be asked to fix this issue.

**Comment by iamAyushChamoli** [comment]
Since @jfmartinz was unable to submit an update within the given time frame, I'll be opening this issue for other contributors

**Comment by gaurayushi** [comment]
i  want to work
