### ISSUE TITLE
[ISSUE] Create a Markdown File for "Learn More" button of the Network And Create Memories Section

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#24]
## Description
In the "Network & Create Memories" segment of the "ABOUT" section, pressing the "Learn More" button currently does nothing. It'll be helpful to create a markdown file named "Network.md" in a separate folder titled "abt" that talks about this section more.

- **Is this a bug or a feature request?**: (Feature)
- **What is the current behavior?**: Nothing happens when we click on "Learn More" in Network And Create Memories segment
- **What is the expected behavior?**: Users get redirected to a markdown file stored in hacktoberfest-24/abt/Network.md

## Screenshots (if applicable)
<img width="398" alt="image" src="https://github.com/user-attachments/assets/9adccce5-639f-4ebb-90ed-d6fa7393f5ba">

## Additional Information
To learn how to create a Markdown file, either study the format "README.md" is written or check out this video: https://youtu.be/_PPWWRV6gbA?si=qPjeA8te4DkfBo5p

**Comment by vineet-53** [comment]
assign to me

**Comment by UmeshKumar0143** [comment]
@iamAyushChamoli  what should be the content of the md file

**Comment by iamAyushChamoli** [comment]
@vineet-53 Please start working on the issue

**Comment by vineet-53** [comment]
> Please start working on the issue

i have created the pull request but wanted to know do i need to include the content on readme file ?

**Comment by iamAyushChamoli** [comment]
Yes, please create content based on the issues already listed in the ISSUES tab. only create ONE pr per issue

**Comment by iamAyushChamoli** [comment]
@vineet-53 are you working on this issue? If you fail to submit an update within 24 hours, you will be unassigned and another contributor may be asked to fix this issue.

**Comment by RishaubKumar** [comment]
assign it to me with hacktoberfest label!

**Comment by vamsi4845** [comment]
@iamAyushChamoli  Could you please assign to me? I'd love to work on it!

**Comment by iamAyushChamoli** [comment]
@vamsi4845 Yes, you can start working please

**Comment by abhayjoshi201** [comment]
The markdown file is still empty, can I write content in it.
