### ISSUE TITLE
[ISSUE] Remove the test data from the participants.js file

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#29]
## Description
Remove entries with have the value of `name: Ayush ChamoliK1` and `name: test` from the `participants.js` file.

- **Is this a bug or a feature request?**: (Bug)
- **What is the current behavior?**:  The test data currently hampers the Leaderboard
- **What is the expected behavior?**: The mentioned data should be removed so that only the data of participants can be visible.

## Screenshots (if applicable)
<img width="686" alt="image" src="https://github.com/user-attachments/assets/09a6fc43-fc78-4866-9b39-df8e983f2fc8">
## Additional Information

Please provide any additional information or context that might help with solving this issue.
NA

**Comment by uday1508** [comment]
@iamAyushChamoli  Please assign the issue
