### ISSUE TITLE
[ISSUE] Create a stat board to tell views on the repository, issues raised and pull requests on readme file

### ISSUE THREAD

**Issue by akhandpratap18** [iamAyushChamoli/hacktoberfest-24#32]
Create a stat board that will tell contributors about how well the repository is growing by telling views on repository,issue raised till now and also pull requests also we can add the contributors profile in a column.

**Comment by akhandpratap18** [comment]
@iamAyushChamoli Assign me this

**Comment by iamAyushChamoli** [comment]
Hi @akhandpratap18 can you link an example of what you are planning to work on?

**Comment by akhandpratap18** [comment]
![WhatsApp Image 2024-10-02 at 16 06 23_740bf996](https://github.com/user-attachments/assets/cf811f15-6804-4cbd-949a-02c8b3b2a502)

@iamAyushChamoli this is on my readme file which tells my stats on Github, similar to it I can add stat board about this repo which can increase the presentation of the repo.

**Comment by iamAyushChamoli** [comment]
Sorry these types of README.md edits can affect the consistency and authenticity of the README.md file. Will close this one for now.
