### ISSUE TITLE
[PR ADD] Hayagreevan V

### ISSUE THREAD

**Issue by hayagreevan-v** [iamAyushChamoli/hacktoberfest-24#38]
## PR Details

Added Hover Animantions to About Card

Name: Hayagreevan V
GitHub Username: hayagreevan-v
PR Number: https://github.com/iamAyushChamoli/hacktoberfest-24/pull/28
Link to PR: https://github.com/iamAyushChamoli/hacktoberfest-24/polls/28
External Repository:
Brief Description of Your Contribution: Added Hover Animantions to About Card

**Comment by iamAyushChamoli** [comment]
@hayagreevan-v  please stick to the issue format that has been specified for [PR ADD] type contributions. Refer the CONTRIBUTING.md for more details.

**Comment by hayagreevan-v** [comment]
##PR Details

Added Hover Animantions to About Card

- **Name**: Hayagreevan V
- **GitHub Username**:  hayagreevan-v
- **PR Number**:  #28 
- **Link to PR**: https://github.com/iamAyushChamoli/hacktoberfest-24/polls/28
- **External Repository**: 
- **Brief Description of Your Contribution**:  Added Hover Animantions to About Card

**Comment by hayagreevan-v** [comment]
## PR Details

Added Hover Animantions to About Card

Name: Hayagreevan V
GitHub Username: hayagreevan-v
PR Number: https://github.com/iamAyushChamoli/hacktoberfest-24/pull/28
Link to PR: https://github.com/iamAyushChamoli/hacktoberfest-24/polls/28
External Repository:
Brief Description of Your Contribution: Added Hover Animantions to About Card
