### ISSUE TITLE
[ISSUE] Making the Card Borders Round

### ISSUE THREAD

**Issue by VikrantKadam028** [iamAyushChamoli/hacktoberfest-24#40]
-Description
Redesigning the cards by rounding there corner to make it smooth and attractive.

**Comment by iamAyushChamoli** [comment]
@VikrantKadam028 are you working on this issue? If you fail to submit an update within 24 hours, you will be unassigned and another contributor may be asked to fix this issue.

**Comment by SaumyaSubham** [comment]
Hii @iamAyushChamoli 
Kindly assign me this issue! I can modify that.

**Comment by iamAyushChamoli** [comment]
Since @VikrantKadam028 failed to submit an update within the given time frame, I will open this ISSUE for other contributors now.

**Comment by AyushiMaithani** [comment]
Please assign this issue to me under hacktoberfest label!!

**Comment by RishaubKumar** [comment]
Please assign this issue to me under hacktoberfest label

**Comment by mohitsinghnegi7** [comment]
Can you tell which card you are talking about?

**Comment by iamAyushChamoli** [comment]
@AyushiMaithani you can start working on this issue
