### ISSUE TITLE
[ISSUE] Fix size of navbar elements and social media icons on footer 

### ISSUE THREAD

**Issue by Mohitranag18** [iamAyushChamoli/hacktoberfest-24#41]
## Description
The size of the navbar elements and social media icons in the footer is inconsistent and doesn't look well-aligned across different screen sizes. We need to ensure that the navbar and footer elements are proportionate and maintain a responsive layout. This issue is coming with desktop screen for mobile the size of elements are right.

- **Is this a bug or a feature request?**: Bug
- **What is the current behavior?**: 

- The navbar elements have varying sizes, making the layout look unbalanced.
- Logo is a little bit bigger and other nav elements are a little bit smaller.
- The social media icons in the footer are too small on the screen size.

- **What is the expected behavior?**: 

- Navbar elements should have uniform size and spacing.
- Social media icons in the footer should scale properly based on screen size and maintain a balanced layout.

![Screenshot (156)](https://github.com/user-attachments/assets/ab74800a-6fa4-402d-b708-ce2079f008b7)

![Screenshot (157)](https://github.com/user-attachments/assets/cb507b5d-bf3a-4faf-93b4-a66e85783717)

**Comment by Mohitranag18** [comment]
i can solve this issue, please assign this issue to me.

**Comment by iamAyushChamoli** [comment]
@Mohitranag18 The footer icons issue has already been solved, you can work on the navbar elements.
