### ISSUE TITLE
[PR Add] Umesh Kumar #37

### ISSUE THREAD

**Issue by UmeshKumar0143** [iamAyushChamoli/hacktoberfest-24#42]
## Description
Add name in participation for the merged pr

Name : Umesh Kumar 
Github Username: UmeshKumar0143
PR no: #37 
description : Increased the size of icons on the footer

**Comment by UmeshKumar0143** [comment]
@iamAyushChamoli  i made a contribution in an external repo also that got merged should i make a new pr add issue for tier 2 and mention both the pr's in it

**Comment by iamAyushChamoli** [comment]
@UmeshKumar0143 You can create a PR for this contribution
