### ISSUE TITLE
[ISSUE] Fix alignment of about section cards

### ISSUE THREAD

**Issue by Mohitranag18** [iamAyushChamoli/hacktoberfest-24#45]
## Description
In about section, cards are left align which is not looking good at desktop screen. we can align them in center and also can increase gap between them. 

- **Is this a bug or a feature request?**: Bug

- **What is the current behavior?**: 
Currently the about sec cards are aligned left side of screen.
Gap between cards are looking a little bit less because there is a lot of blank space is empty in that section's right side.

- **What is the expected behavior?**: 
Cards should be aligned at the center.
Gap between cards should be increase a little bit.

## Screenshots 
![Screenshot 2024-10-02 at 23-26-10 HacktoberFest'24](https://github.com/user-attachments/assets/bcab0fc3-80ad-40b5-a862-58bbdc4c66ef)

**Comment by Mohitranag18** [comment]
please assign this issue to me i will solve it.

**Comment by iamAyushChamoli** [comment]
@Mohitranag18 You can start working on this
