### ISSUE TITLE
[ISSUE] Add the hover effect

### ISSUE THREAD

**Issue by SaumyaSubham** [iamAyushChamoli/hacktoberfest-24#47]
## Description
Hello @iamAyushChamoli 

I want to add the hover effect on the social media icons in the footer so that the users can easily navigate to the social media handles.
Kindly assign me this issue under Hacktoberfest 2024

**Comment by iamAyushChamoli** [comment]
@SaumyaSubham that'll be a very basic contribution and add very little to the repository. That's probably just one or two more words. Please suggest a more productive change or read the CONTRIBUTING.md if you want to bring in your external contribution
