### ISSUE TITLE
[PR ADD] Umesh Kumar 

### ISSUE THREAD

**Issue by UmeshKumar0143** [iamAyushChamoli/hacktoberfest-24#51]
## PR Details
 
- **Name**:  Umesh Kumar
- **GitHub Username**:  UmeshKumar0143
- **External PR's Number**: 30 , 35 , 41
- **Link to External PR**: 
-  https://github.com/AkshitLakhera/PenCraft-Full-Stack-Blogging-Application/pull/30 
- https://github.com/AkshitLakhera/PenCraft-Full-Stack-Blogging-Application/pull/35,
- https://github.com/AkshitLakhera/PenCraft-Full-Stack-Blogging-Application/pull/41
- **External Repository**:  https://github.com/AkshitLakhera/PenCraft-Full-Stack-Blogging-Application
- **Brief Description of Your Contribution**: 
Made a loader in the sign in and sign up page with error message on any error fixed Comment Section issues

**Comment by iamAyushChamoli** [comment]
@UmeshKumar0143  you can create a pr for adding your details in the participants.js
