### ISSUE TITLE
[ISSUE] The NavSection Overlaps NavIcon in mobile view

### ISSUE THREAD

**Issue by Divyanshu960** [iamAyushChamoli/hacktoberfest-24#53]
## Description
Please provide a clear and concise description of the issue or feature you are working on.

- **Is this a bug or a feature request?**: Bug
- **What is the current behavior?**:  It overlaps the NavIcon in Mobile view
- **What is the expected behavior?**: The expected behaviour is that it should not overlap and be slightly positioned lower so that it doesnt overlap the NavIcon

## Steps to Reproduce (for bugs)
Please list the steps to reproduce the bug if applicable.

1. Open the website in Mobile View
2. Click on the Hamburger Icon
3. You'll see that the Navigation Section is Overlapping the Icon

## Screenshots (if applicable)
See the Icon below
![image](https://github.com/user-attachments/assets/0df17986-9f78-4388-a4da-46dcdee24e36)
See how it gets cut when the Hamburger Icon is clicked
![image](https://github.com/user-attachments/assets/8f8a8eef-36a7-4790-ae7c-8402650a8f48)

## Additional Information
I have completed this feature. Please assign it to me for hacktoberfest and allow me to create Pull Request.

**Comment by Divyanshu960** [comment]
I have fixed the Issue , it looks fine now 
![image](https://github.com/user-attachments/assets/d8d3fe26-b5ac-43f5-9dda-ed6d113a6d25)

**Comment by vivekrawat21** [comment]
sure go ahead and raise a pull req
