### ISSUE TITLE
[ISSUE] Add Badge.md

### ISSUE THREAD

**Issue by SaumyaSubham** [iamAyushChamoli/hacktoberfest-24#55]
## Description
Hii @iamAyushChamoli 
I want to add details in Badge.md, Learn Git & Github.md, Explore Open Source.md, Compete With Your Peers.md, Build Your Github Portfolio.md, and Network & Create Memories.md for better documentations of these cards.
Kindly assign me this issue under hacktoberfest 2024.

**Comment by iamAyushChamoli** [comment]
@SaumyaSubham these tasks are currently assigned to other contributors. You can check out ISSUES tab for other issues that need attention or read the CONTRIBUTING.md file to bring in issues from other repos
