### ISSUE TITLE
[ISSUE] Navbar not responsive as you scroll the website

### ISSUE THREAD

**Issue by Pratik2401** [iamAyushChamoli/hacktoberfest-24#58]
## Description
Please provide a clear and concise description of the issue or feature you are working on.

- **Is this a bug or a feature request?**: Bug
- **What is the current behavior?**:  The Navbar active tag acts only when it is clicked and not when scrolled
- **What is the expected behavior?**:The Navbar active tag should shift from one nav link to another 

## Steps to Reproduce (for bugs)
Please list the steps to reproduce the bug if applicable.
1. Click on any nav-link
2. And Scroll the website
3. Observe the Active tag of navbar

## Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/5d2eaa8d-6737-453b-ba79-1cf6e0c60d07)

## Additional Information
Please provide any additional information or context that might help with solving this issue.

**Comment by Pratik2401** [comment]
Please assign me under Hacktoberfest 2024

**Comment by iamAyushChamoli** [comment]
@Pratik2401 you can start
