### ISSUE TITLE
"Guidelines link not redirecting to another page"

### ISSUE THREAD

**Issue by Lokeshsuwalka05** [iamAyushChamoli/hacktoberfest-24#59]
Expected Behavior: Clicking on the "Guidelines" link should navigate the user to a new page displaying the guidelines.

Can you assign this issue to me under Hactoberfest'24

**Comment by iamAyushChamoli** [comment]
@Lokeshsuwalka05 it seems to be working on my end. Can you please specify which segment you're talking about? Thanks

**Comment by Lokeshsuwalka05** [comment]
Now it is working from my side also
i think it's my mistake

**Comment by Lokeshsuwalka05** [comment]
Contribution Guidelines


https://github.com/user-attachments/assets/78606ac2-2de9-455f-b967-6d309fd7add3

**Comment by iamAyushChamoli** [comment]
@Lokeshsuwalka05 do you mean that it is not opening the link in a new tab? You can submit a PR

**Comment by Lokeshsuwalka05** [comment]
Yes,
ok i'll do it by tomorrow
