### ISSUE TITLE
[PR ADD] <Pratik Mali>

### ISSUE THREAD

**Issue by Pratik2401** [iamAyushChamoli/hacktoberfest-24#66]
## PR Details
Please provide the following details about your external contribution:

- **Name**: Pratiik mali
- **GitHub Username**: Pratik2401
- **External PR Number**: #61 
- **Link to External PR**: https://github.com/iamAyushChamoli/hacktoberfest-24/pull/61
- **External Repository**: https://github.com/Pratik2401/hacktoberfest-24
- **Brief Description of Your Contribution**: navbar reponsive

Once your contribution has been verified by the maintainers, you will be instructed to update the `participants/participants.js` file and create a pull request.

**Comment by vivekrawat21** [comment]
@Pratik2401 go ahead and create a pr

**Comment by Pratik2401** [comment]
But it haven't updated in Hacktoberfest is there something I need to do @iamAyushChamoli

**Comment by iamAyushChamoli** [comment]
@Pratik2401 it takes some time to reflect on the profile.

**Comment by Pratik2401** [comment]
Thanks buddyy

**Comment by Pratik2401** [comment]
@iamAyushChamoli maybe you have to add Hacktober accepted label something I read it on the website
