### ISSUE TITLE
Not an ISSUE

### ISSUE THREAD

**Issue by Divyanshu960** [iamAyushChamoli/hacktoberfest-24#67]
Not an issue but I wanted to ask the maintainers to please assign Hacktoberfest-accepted and participation-eligible labels to my PR
![image](https://github.com/user-attachments/assets/049e759c-a0bc-42c3-80ce-e135cc287000)
Just like other contributors.
![image](https://github.com/user-attachments/assets/240df154-2f67-448c-baf7-0dcea9616de4)

I am new to this , kindly guide .

**Comment by iamAyushChamoli** [comment]
@Divyanshu960 Have added it now. Thank you for bringing my attention to it :)
