### ISSUE TITLE
"Add Scroll to Top Button with Smooth Scrolling"

### ISSUE THREAD

**Issue by Lokeshsuwalka05** [iamAyushChamoli/hacktoberfest-24#71]
This update introduces a "Scroll to Top" button that appears when users scroll down the page, enhancing navigation on long pages. The button, when clicked, smoothly scrolls the user back to the top of the page. The feature includes:

1)A floating button styled with CSS, positioned at the bottom-right corner of the screen.
2)JavaScript functionality that toggles the button's visibility based on scroll position.
3)Smooth scrolling behavior to provide a seamless user experience when navigating back to the top.

**Comment by Lokeshsuwalka05** [comment]
if Possible then assign this issue to me under Hacktoberfest'24

**Comment by iamAyushChamoli** [comment]
@Lokeshsuwalka05 you've been assigned an issue already, please get a PR merged for that issue before you ask to be assigned to another issue!

**Comment by Lokeshsuwalka05** [comment]
Ok

**Comment by Lokeshsuwalka05** [comment]
But,Don't assign this issue to anyone

**Comment by Lokeshsuwalka05** [comment]
i resolved issue #59 can i work on this issue.

**Comment by Lokeshsuwalka05** [comment]
Is this repo excluded from the Hacktoberfest??

**Comment by raj-adi00** [comment]
@iamAyushChamoli  Can you please assign this issue to me unnder HacktoberFest. I will add a button when user scrolls down at bottom and allow user to scroll  up with smooth scrolling
