### ISSUE TITLE
[ISSUE] Graphic overlapping with the "Leaderboard is live" text 

### ISSUE THREAD

**Issue by adityanandanx** [iamAyushChamoli/hacktoberfest-24#74]
## Description
Please provide a clear and concise description of the issue or feature you are working on.

- **Is this a bug or a feature request?**: Bug
- **What is the current behavior?**: Overlapping
![image](https://github.com/user-attachments/assets/81443815-4e66-4bd7-ab1a-be9f49a07c96)

- **What is the expected behavior?**: No Overlapping
![image](https://github.com/user-attachments/assets/e098f436-6787-4e0f-8902-bff257fe0e26)

## Steps to Reproduce (for bugs)
Please list the steps to reproduce the bug if applicable.

1. Just scroll the website at `1920x1080` resolution

## Screenshots (if applicable)
Already added above

## Additional Information
-

**Comment by vivekrawat21** [comment]
Hi @adityanandanx thankyou for  finding this bug if you are willing to work on this issue i'll assign it to you.

**Comment by adityanandanx** [comment]
Thanks!
Please assign this to me. 🙂

**Comment by vivekrawat21** [comment]
@adityanandanx assigned to you go can go ahead and create a PR
