### ISSUE TITLE
[ISSUE] Update cursor style to pointer for navigation elements

### ISSUE THREAD

**Issue by kaushikikhabri** [iamAyushChamoli/hacktoberfest-24#78]
**Description:** The navigation elements ("Home," "About," "Partners," "Leaderboard") are clickable, but the cursor displayed is the **text cursor instead of the pointer cursor.** This can lead to confusion and negatively impact user experience. The cursor should change to a pointer when hovering over these elements to make it more user-friendly.

**Affected Elements:**

Home
About
Partners
Leaderboard

**Expected Behavior:** When hovering over the "Home," "About," "Partners," and "Leaderboard" elements in the navigation, the cursor should change to a pointer, indicating the elements are clickable.

**Steps to Reproduce:**

1. Navigate to the website.
2. Hover over the "Home," "About," "Partners," or "Leaderboard" navigation items.
3. Observe the text cursor instead of the expected pointer cursor.

![issue](https://github.com/user-attachments/assets/90690e94-a669-40e3-8ccd-405516979b7f)

**Comment by Ankitmohanty2** [comment]
can i work on this issue??

**Comment by vivekrawat21** [comment]
@kaushikikhabri thankyou for finding this issue.
