### ISSUE TITLE
[ISSUE] Leaderboard Section Needs Redesign for Better Readability and Aesthetics

### ISSUE THREAD

**Issue by kaushikikhabri** [iamAyushChamoli/hacktoberfest-24#84]
The leaderboard section is currently not very readable and takes up excessive space on the page. It appears to be unsorted based on rank, and the images associated with contributors occupy too much space, making the design visually unappealing.

**Is this a bug or a feature request?**: Feature
**What is the current behavior?:** The leaderboard displays contributors in a cluttered format, with images taking up significant space and lacking clear ranking.
**What is the expected behavior?:** A redesigned leaderboard where contributors are listed one below the other, with their ranks clearly highlighted. The design should be responsive and visually appealing, with a cleaner layout.

![image](https://github.com/user-attachments/assets/2e398380-6178-45d3-9983-e1c3fe4acee5)

**Comment by kaushikikhabri** [comment]
@iamAyushChamoli **Please assign me this feature.**

**Comment by iamAyushChamoli** [comment]
@kaushikikhabri please submit a working prototype of the proposed change in a PR.

**Comment by iamAyushChamoli** [comment]
@kaushikikhabri the PR that you introduced induced loss of some participant data. Please bear with us and resubmit another PR with updated participant details when I'll instruct you to do so. Thanks!

**Comment by vamsi4845** [comment]
@iamAyushChamoli Could you please assign to me? I'd love to work on it!

**Comment by iamAyushChamoli** [comment]
@vamsi4845 you can start working on it

**Comment by vamsi4845** [comment]
@iamAyushChamoli 
![image](https://github.com/user-attachments/assets/8a28f1ae-7067-4749-b73e-9da74e1c1177)

**Comment by vamsi4845** [comment]
I've designed the leaderboard, let me know if this looks good or needs any changes so that I can create a PR
![image](https://github.com/user-attachments/assets/04d1ac7c-bab6-496a-8b7d-2ef26fa745ae)

**Comment by iamAyushChamoli** [comment]
The grayish background color needs to be changed to something that aligns to the aesthetic of the website better.
Plus, you need to only showcase the link to the LATEST PR in the last column.

**Comment by vamsi4845** [comment]
> @iamAyushChamoli This one is a recent PR of myn which got merged but its tagged as excluded #24 #127 ![image](https://private-user-images.githubusercontent.com/39260099/378188476-8a28f1ae-7067-4749-b73e-9da74e1c1177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjcwODAsIm5iZiI6MTcyOTUyNjc4MCwicGF0aCI6Ii8zOTI2MDA5OS8zNzgxODg0NzYtOGEyOGYxYWUtNzA2Ny00NzQ5LWI3M2UtOWRhNzRlMWMxMTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2MDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNDJmOTM3NGI1NmE5ZWZjZGY0MjdiZTcyYTZhNzQ2NTdhMDAyYzkzOTQ4ZTc5OTg5N2I1ZTNlOWVkOWI3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O68nUQYazkzfop--gl3JhUD_J7DpyS0_FTv23qZS-ps) ig you need to use hacktoberfest-accepted label instead of hacktoberfest,maybe you can add the label now too ![image](https://private-user-images.githubusercontent.com/39260099/378188677-6649720e-7913-4b5e-a90d-5d64636a55c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjcwODAsIm5iZiI6MTcyOTUyNjc4MCwicGF0aCI6Ii8zOTI2MDA5OS8zNzgxODg2NzctNjY0OTcyMGUtNzkxMy00YjVlLWE5MGQtNWQ2NDYzNmE1NWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2MDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZTA1YTUwYTU1MDM1NDYzMzgzMTI3OGNiMTllYTRiYzliZmI2MDljNGRkYTUzNmMxNmFhOTk2YzdiMTg5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZVTqNDLwSlXfSEIsG_Vvcf1xxwj9CFljLf54nvrV67I)

Check this once @iamAyushChamoli

**Comment by iamAyushChamoli** [comment]
@vamsi4845 please refer to the current leaderboard and checkout the hover effects when you hover on a participant tile. Add similar hover effects. Also it'd be nice to have a gold badge besides the first participant (after the latest PR column), silver besides the second and bronze besides the third.

Also the current code is introducing inefficient rendering of some images (check out vineet's profile image) 

Please fix all these issues

**Comment by vamsi4845** [comment]
@iamAyushChamoli Fixed everything
![image](https://github.com/user-attachments/assets/ab242b33-67c9-4a9d-adf1-97a53e6bc6e3)
