### ISSUE TITLE
Improve Responsiveness of Leaderboard Cards and Align Badges Card for Improved Visuals

### ISSUE THREAD

**Issue by Mayank8881** [iamAyushChamoli/hacktoberfest-24#93]
**Title:** Center Leaderboard Card and Align Badges Card for Improved Visuals

**Description:**  
The current layout of the leaderboard and badges cards is not visually appealing and requires adjustments to enhance user experience. The following changes are needed:

1. **Center the Leaderboard Card:**
   - The leaderboard card is currently off-center, which affects the overall visual balance of the page. Centering this card will improve its prominence and create a more cohesive layout.

2. **Align Badges Card:**
   - The badges card is misaligned, leading to a disorganized appearance. Proper alignment of the badges will improve clarity and make the interface more user-friendly.

3. **Improve Responsiveness of Leaderboard Card:**
   - The leaderboard cards are not well responsive, causing layout issues on smaller screens. Ensuring the cards adjust appropriately across different screen sizes is essential for a seamless user experience.

**Screenshot Reference:** 
![Screenshot 2024-10-06 023120](https://github.com/user-attachments/assets/b2692241-ad81-40f3-a4fa-3df9e86b82ba)
![Screenshot (17)](https://github.com/user-attachments/assets/f283392d-66fb-40c1-8941-f08b7366143f)

**Proposed Solution:**
- Adjust the CSS properties of the leaderboard card to center it on the page.
- Review the layout of the badges card and ensure that all badges are evenly spaced and aligned properly.
- Implement responsive design techniques to ensure the leaderboard cards adapt well to various screen sizes.
- Test the changes across different devices to ensure consistency in alignment and visual appeal.
---
Request:
I would like to contribute this solution as part of Hacktoberfest. Please assign this issue to me and add the Hacktoberfest label.

Thank you!

**Comment by iamAyushChamoli** [comment]
@Mayank8881 we're currently considering a revamp of the leaderboard design so this solution might not be needed. Please check out other open issues in the repository.
